services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
  chroma:
    image: chromadb/chroma:1.5.6.dev60
    volumes:
      - chroma_data:/data
    ports:
      - "8000:8000"
    command: chroma run --path /data

volumes:
  redis_data:
  chroma_data: